name: Build Service

on:
  workflow_dispatch:
  pull_request:
    paths-ignore: ['*.md']
    branches: ['master']
  push:
    paths-ignore: ['*.md']
    branches: ['master']

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Setup build environment
        uses: start9labs/shared-workflows/.github/actions/setup-build-env@master

      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Find or create developer signing key
        run: |
          if [ -n "${{ secrets.DEV_KEY }}" ]; then
            mkdir -p ~/.startos
            printf '%s' "${{ secrets.DEV_KEY }}" > ~/.startos/developer.key.pem
          else
            start-cli init-key
          fi
        shell: bash

      - name: Build service packages
        run: |
          RUST_LOG=debug RUST_BACKTRACE=1 make
          echo ""
          echo "SHA256SUMs:"
          sha256sum *.s9pk
        shell: bash
